CREATE TABLE INSTITUTO (
  Cod_ins INT,
  Nombre VARCHAR(40),
  Hora_apertura TIME,
  Hora_cierre TIME,
  PRIMARY KEY (Cod_ins)
) ENGINE=InnoDB;

CREATE TABLE PERSONA (
  DNI VARCHAR(10),
  Cod_ins INT,
  PRIMARY KEY (DNI),
  FOREIGN KEY (Cod_ins) REFERENCES INSTITUTO(Cod_ins)
) ENGINE=InnoDB;

CREATE TABLE DEPARTAMENTO (
  Cod_dep VARCHAR(7),
  Nombre VARCHAR(8),
  PRIMARY KEY (Cod_dep)
) ENGINE=InnoDB;

CREATE TABLE CURSO (
  N_curso INT,
  Num_alumno INT,
  DNI VARCHAR(10),
  PRIMARY KEY (N_curso),
  FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
) ENGINE=InnoDB;

CREATE TABLE EMPLEADO (
  DNI VARCHAR(10),
  NSS BIGINT,
  Nombre VARCHAR(8),
  Apellidos VARCHAR(20),
  Fecha_nacimiento DATE,
  Salario DECIMAL(10,2),
  Num_cuenta_banc BIGINT,
  PRIMARY KEY (DNI),
  FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
) ENGINE=InnoDB;

CREATE TABLE ESTUDIANTE (
  DNI VARCHAR(10),
  Cod_ficha VARCHAR(5),
  Nombre VARCHAR(8),
  Apellidos VARCHAR(20),
  Genero VARCHAR(9),
  Fecha_nacimiento DATE,
  Repetidor VARCHAR(13),
  N_curso INT,
  PRIMARY KEY (DNI),
  FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
  FOREIGN KEY (N_curso) REFERENCES CURSO(N_curso)
) ENGINE=InnoDB;

CREATE TABLE PERSONAL_MANTENIMIENTO (
  DNI VARCHAR(10),
  Horario TIME,
  PRIMARY KEY (DNI),
  FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
) ENGINE=InnoDB;

CREATE TABLE DOCENTE (
  DNI VARCHAR(10),
  Director VARCHAR(6),
  Cod_dep VARCHAR(7),
  PRIMARY KEY (DNI),
  FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
  FOREIGN KEY (Cod_dep) REFERENCES DEPARTAMENTO(Cod_dep)
) ENGINE=InnoDB;

CREATE TABLE AULA (
  Cod_aula VARCHAR(4),
  Nombre VARCHAR(8),
  Cap_max INT,
  N_curso INT,
  PRIMARY KEY (Cod_aula),
  FOREIGN KEY (N_curso) REFERENCES CURSO(N_curso)
) ENGINE=InnoDB;

CREATE TABLE ASIGNATURA (
  Cod_asig VARCHAR(12),
  Nombre VARCHAR(8),
  Cod_dep VARCHAR(7),
  PRIMARY KEY (Cod_asig),
  FOREIGN KEY (Cod_dep) REFERENCES DEPARTAMENTO(Cod_dep)
) ENGINE=InnoDB;

CREATE TABLE CURSA (
  DNI VARCHAR(10),
  Cod_asig VARCHAR(12),
  Nota_final DECIMAL(4,2),
  PRIMARY KEY (DNI, Cod_asig),
  FOREIGN KEY (DNI) REFERENCES ESTUDIANTE(DNI),
  FOREIGN KEY (Cod_asig) REFERENCES ASIGNATURA(Cod_asig)
) ENGINE=InnoDB;

CREATE TABLE DA (
  DNI VARCHAR(10),
  Cod_asig VARCHAR(12),
  PRIMARY KEY (DNI, Cod_asig),
  FOREIGN KEY (DNI) REFERENCES DOCENTE(DNI),
  FOREIGN KEY (Cod_asig) REFERENCES ASIGNATURA(Cod_asig)
) ENGINE=InnoDB;

