/*
ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER InstitutoTrabajo IDENTIFIED BY InstitutoTrabajo;
GRANT CONNECT, RESOURCE, DBA TO InstitutoTrabajo;
*/
CREATE TABLE INSTITUTO
(
	Cod_ins NUMBER NOT NULL,
	Nombre VARCHAR2(50),
	Hora_apertura DATE,
	Hora_cierre DATE,

CONSTRAINT PK_INSTITUTO PRIMARY KEY (Cod_ins),
CONSTRAINT CK_Hora CHECK (Hora_apertura<Hora_cierre)
);
CREATE TABLE PERSONA
(
	DNI VARCHAR2(9),
	Cod_ins NUMBER,
	
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
CONSTRAINT FK1_PERSONA FOREIGN KEY (Cod_ins) REFERENCES INSTITUTO(Cod_ins)
);
CREATE TABLE EMPLEADO
(
	DNI VARCHAR2(9),
	NSS NUMBER(12) UNIQUE,
	Nombre VARCHAR2(50),
	Apellidos VARCHAR2(50),
	Fecha_nacimiento DATE,
	Salario NUMBER,
	Num_cuenta_banc VARCHAR2(10) UNIQUE,
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);
CREATE TABLE DEPARTAMENTO
(
	Cod_dep VARCHAR2(10),
	Nombre VARCHAR2(50),
	
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (Cod_dep)
);
CREATE TABLE CURSO 
(
	Nº_curso NUMBER,
	Num_alumn NUMBER,
	DNI VARCHAR2(9),
CONSTRAINT PK_CURSO PRIMARY KEY (Nº_curso),
CONSTRAINT FK1_CURSO FOREIGN KEY (DNI)REFERENCES PERSONA(DNI)
);
CREATE TABLE ESTUDIANTE
(
	DNI VARCHAR2(9),
	Cod_ficha NUMBER,
	Nombre VARCHAR2(50),
	Apellidos VARCHAR2(50),
	Genero VARCHAR2(10),
	Fecha_nacimiento DATE,
	Repetidor VARCHAR2(2),
	Nº_curso NUMBER,
	
CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (DNI),
CONSTRAINT FK1_ESTUDIANTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_ESTUDIANTE FOREIGN KEY (Nº_curso) REFERENCES CURSO(Nº_curso),
CONSTRAINT CK_DNI CHECK (REGEXP_LIKE(DNI, '^\d{8}[A-Z]$')),
CONSTRAINT CK_Repetidor CHECK (Repetidor IN ('Si', 'No')),
CONSTRAINT CK_Genero CHECK (Genero IN ('M', 'F'))
);
CREATE TABLE PERSONAL_MANTENIMIENTO
(
	DNI VARCHAR2(9),
	Horario DATE,
	
CONSTRAINT PK_PERSONAL_MANTENIMIENTO PRIMARY KEY (DNI),
CONSTRAINT FK1_PERSONAL_MANTENIMIENTO FOREIGN KEY (DNI)REFERENCES PERSONA(DNI)
);
CREATE TABLE DOCENTE 
(
	DNI VARCHAR2(9),
	Director VARCHAR2(2),
	Cod_dep VARCHAR2(10),
	
CONSTRAINT PK_DOCENTE PRIMARY KEY (DNI),
CONSTRAINT FK1_DOCENTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_DOCENTE FOREIGN KEY (Cod_dep) REFERENCES DEPARTAMENTO(Cod_dep)
);
CREATE TABLE AULA
(
	Cod_aula NUMBER,
	Nombre VARCHAR2(50),
	Cap_max NUMBER,
	Nº_curso NUMBER,
	
CONSTRAINT PK_AULA PRIMARY KEY (Cod_aula),
CONSTRAINT FK1_AULA FOREIGN KEY (Nº_curso) REFERENCES CURSO(Nº_curso)
);
CREATE TABLE ASIGNATURA
(
	Cod_asig NUMBER,
	Nombre VARCHAR2(50),
	Cod_dep VARCHAR2(10),
	
CONSTRAINT PK_ASIGNATURA PRIMARY KEY (Cod_asig),
CONSTRAINT FK1_ASIGNATURA FOREIGN KEY (Cod_dep) REFERENCES DEPARTAMENTO(Cod_dep)
);
CREATE TABLE CURSA
(
	DNI VARCHAR2(9),
	Cod_asig NUMBER,
	Nota_final NUMBER(2,2),
	
CONSTRAINT PK_CURSA PRIMARY KEY (DNI,Cod_asig),
CONSTRAINT FK1_CURSA FOREIGN KEY (DNI)REFERENCES ESTUDIANTE(DNI),
CONSTRAINT FK2_CURSA FOREIGN KEY (cod_asig)REFERENCES ASIGNATURA(Cod_asig),
CONSTRAINT CK_Nota_final CHECK (Nota_final >= 0 AND Nota_final <= 10)
);
CREATE TABLE DA
(
	DNI VARCHAR2(9),
	Cod_asig NUMBER,
CONSTRAINT PK_DA PRIMARY KEY (DNI,Cod_asig),
CONSTRAINT FK1_DA FOREIGN KEY (DNI)REFERENCES DOCENTE(DNI),
CONSTRAINT FK2_DA FOREIGN KEY (cod_asig)REFERENCES ASIGNATURA(Cod_asig)
);










