CREATE TABLE INSTITUTO
(
COD_INST NUMBER(10),
NOMBRE VARCHAR2(100),
HORA_APERTURA NUMBER(4,2),
HORA_CIERRE NUMBER(4,2),
CONSTRAINT PK_INSTITUTO PRIMARY KEY (COD_INST),
CONSTRAINT CK1_INSTITUTO CHECK (HORA_CIERRE>HORA_APERTURA)
);

CREATE TABLE DEPARTAMENTO
(
COD_DEP NUMBER(10),
NOMBRE VARCHAR2(100),
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEP)
);

CREATE TABLE PERSONA
(
DNI VARCHAR2(9),
COD_INST NUMBER(10),
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
CONSTRAINT FK1_PERSONA FOREIGN KEY (COD_INST) REFERENCES INSTITUTO(COD_INST),
CONSTRAINT CK1_PERSONA CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}[A-Z]$'))
);

CREATE TABLE EMPLEADO
(
DNI VARCHAR2(9),
NSS NUMBER(12),
NOMBRE VARCHAR2(50),
APELLIDOS VARCHAR2(100),
FECHA_NACIMIENTO DATE,
SALARIO NUMBER(8,2),
NUM_CUENTA_BANC VARCHAR2(30),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT UQ1_EMPLEADO UNIQUE (NSS),
CONSTRAINT UQ2_EMPLEADO UNIQUE (NUM_CUENTA_BANC)
);

CREATE TABLE PERSONAL_MANTENIMIENTO
(
DNI VARCHAR2(9),
HORARIO VARCHAR2(50),
CONSTRAINT PK_PERSONAL_MANTENIMIENTO PRIMARY KEY (DNI),
CONSTRAINT FK1_PERSONAL_MANTENIMIENTO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE DOCENTE
(
DNI VARCHAR2(9),
DIRECTOR VARCHAR2(2),
COD_DEP NUMBER(10),
CONSTRAINT PK_DOCENTE PRIMARY KEY (DNI),
CONSTRAINT FK1_DOCENTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_DOCENTE FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE CURSO
(
NUM_CURSO NUMBER(10),
NUM_ALUMN NUMBER(10),
DNI_TUTOR VARCHAR2(9),
CONSTRAINT PK_CURSO PRIMARY KEY (NUM_CURSO),
CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_TUTOR) REFERENCES PERSONA(DNI)
);

CREATE TABLE AULA
(
COD_AULA NUMBER(10),
NOMBRE VARCHAR2(50),
CAP_MAX NUMBER(30),
NUM_CURSO NUMBER(1),
CONSTRAINT PK_AULA PRIMARY KEY (COD_AULA),
CONSTRAINT FK1_AULA FOREIGN KEY (NUM_CURSO) REFERENCES CURSO(NUM_CURSO)
);

CREATE TABLE ASIGNATURA
(
COD_ASIG NUMBER(4),
NOMBRE VARCHAR2(100),
COD_DEP NUMBER(10),
CONSTRAINT PK_ASIGNATURA PRIMARY KEY (COD_ASIG),
CONSTRAINT FK1_ASIGNATURA FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE ESTUDIANTE
(
DNI VARCHAR2(9),
COD_FICHA NUMBER(4),
NOMBRE VARCHAR2(50),
APELLIDOS VARCHAR2(100),
GENERO VARCHAR2(1),
FECHA_NACIMIENTO DATE,
REPETIDOR VARCHAR2(2),
NUM_CURSO NUMBER(1),
CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (DNI),
CONSTRAINT FK1_ESTUDIANTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_ESTUDIANTE FOREIGN KEY (NUM_CURSO) REFERENCES CURSO(NUM_CURSO),
CONSTRAINT CK1_ESTUDIANTE CHECK (GENERO IN ('M', 'F')),
CONSTRAINT CK2_ESTUDIANTE CHECK (REPETIDOR IN ('Si', 'No'))
);

CREATE TABLE CURSA
(
DNI VARCHAR2(9),
COD_ASIG NUMBER(4),
NOTA_FINAL NUMBER(4,2),
CONSTRAINT PK_CURSA PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT FK1_CURSA FOREIGN KEY (DNI) REFERENCES ESTUDIANTE(DNI),
CONSTRAINT FK2_CURSA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG),
CONSTRAINT CK1_CURSA CHECK (NOTA_FINAL BETWEEN 0 AND 10)
);

CREATE TABLE DA
(
DNI VARCHAR2(9),
COD_ASIG NUMBER(4),
CONSTRAINT PK_DA PRIMARY KEY (DNI, COD_ASIG),
CONSTRAINT FK1_DA FOREIGN KEY (DNI) REFERENCES DOCENTE(DNI),
CONSTRAINT FK2_DA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
);

ALTER TABLE INSTITUTO MODIFY COD_INST NOT NULL;