alter session set "_oracle_script"=true;  
create user trabajo identified by trabajo;
GRANT CONNECT, RESOURCE, DBA TO trabajo;

CREATE TABLE INSTITUTO
(
Cod_ins NUMBER,
Nombre VARCHAR2(40),
Hora_apertura DATE,
Hora_cierre DATE,

CONSTRAINT PK_INSTITUTO PRIMARY KEY (Cod_ins)

);
CREATE TABLE PERSONA 
(
DNI VARCHAR2(10),
Cod_ins NUMBER(15),

CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
CONSTRAINT FK1_PERSONA FOREIGN KEY (Cod_ins) REFERENCES INSTITUTO(Cod_ins)

);
CREATE TABLE EMPLEADO
(
DNI VARCHAR2(10),
NSS NUMBER (20),
Nombre VARCHAR2 (8),
Apellidos VARCHAR2 (20),
Fecha_nacimiento DATE,
Salario NUMBER,
Num_cuenta_banc NUMBER,

CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);
CREATE TABLE DEPARTAMENTO 
(
Cod_dep VARCHAR2(7),
Nombre VARCHAR2(8),

CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (Cod_dep)
);
CREATE TABLE CURSO
(
N_curso NUMBER,
Num_alumno NUMBER,
DNI VARCHAR2(10),

CONSTRAINT PK_CURSO PRIMARY KEY (N_curso),
CONSTRAINT FK1_CURSO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);
CREATE TABLE ESTUDIANTE
(
DNI VARCHAR2(10),
Cod_ficha VARCHAR2(5),
Nombre VARCHAR2 (8),
Apellidos VARCHAR2 (20),
Genero VARCHAR2(9),
Fecha_nacimiento DATE,
Repetidor VARCHAR2(13),
N_curso NUMBER,

CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (DNI),
CONSTRAINT FK1_ESTUDIANTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_ESTUDIANTE FOREIGN KEY (N_curso) REFERENCES CURSO(N_curso)
);
CREATE TABLE PERSONAL_MANTENIMIENTO 
(
DNI VARCHAR2(10),
Horario DATE,

CONSTRAINT PK_PERSONAL_MANTENIMIENTO  PRIMARY KEY (DNI),
CONSTRAINT FK1_PERSONAL_MANTENIMIENTO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);
CREATE TABLE DOCENTE 
(
DNI VARCHAR2(10),
Director VARCHAR2(6),
Cod_dep VARCHAR2(7),

CONSTRAINT PK_DOCENTE PRIMARY KEY (DNI),
CONSTRAINT FK1_DOCENTE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK1_DOCENTE FOREIGN KEY (Cod_dep) REFERENCES DEPARTAMENTO(Cod_dep)
);
CREATE TABLE AULA
(
Cod_aula VARCHAR2(4),
Nombre VARCHAR2 (8),
Cap_max NUMBER,
N_curso NUMBER,

CONSTRAINT PK_AULA PRIMARY KEY (Cod_aula),
CONSTRAINT FK1_AULA FOREIGN KEY (N_curso) REFERENCES CURSO(N_curso)
);
CREATE TABLE ASIGNATURA 
(
Cod_asig VARCHAR2(12),
Nombre VARCHAR2 (8),

CONSTRAINT PK_ASIGNATURA PRIMARY KEY (Cod_asig),
CONSTRAINT FK1_ASIGNATURA FOREIGN KEY (Cod_dep) REFERENCES DEPARTAMENTO(Cod_dep)
);
CREATE TABLE CURSA
(
DNI VARCHAR2(10),
Nota_final NUMBER,

CONSTRAINT PK_CURSA PRIMARY KEY (DNI),
CONSTRAINT FK1_CURSA FOREIGN KEY DNI REFERENCES ESTUDIANTE(DNI),
CONSTRAINT FK1_CURSA FOREIGN KEY Cod_asig REFERENCES ASIGNATURA(Cod_asig)
);
CREATE TABLE DA 
DNI VARCHAR2(10),
Cod_asig VARCHAR2(12),
CONSTRAINT PK_DA PRIMARY KEY (DNI,Cod_asig),
CONSTRAINT FK1_DA FOREIGN KEY DNI REFERENCES DOCENTE(DNI),
CONSTRAINT FK1_DA FOREIGN KEY Cod_asig REFERENCES ASIGNATURA(Cod_asig)
);




